language: python
python:
  - "2.6"
  - "2.7"
# command to install dependencies
install: 
    - pip install -r travis.txt --use-mirrors
    - python setup.py develop
script: python example/manage.py test follow -v2
  